// packages/react-example/src/client/app/components/UserDisplay/UserDisplay.tsx
import * as React from 'react';
import { useState } from 'react';
import { userQuery } from '../../requests/user';
import { useQuery } from '@fetcher/react';

interface Props {
    variant: number;
}

const UserDisplay: React.FC<Props> = ({ variant }) => {
    const [userId, setUserId] = useState(1);

    const { data, error, loading, refetch, abort } = useQuery(
        userQuery({
            requestParams: { pathParams: { id: userId } },
            fetchPolicy: variant === 1 ? 'cache-and-network' : variant === 2 ? 'cache-only' : 'no-cache',
            pollInterval: 100,
            lazy: false,
        }),
    );

    console.log('Render', variant, data?.name, error?.message, loading);

    return (
        <div>
            <button onClick={refetch}>Refetch</button>
            <button onClick={abort}>Abort</button>
            <button onClick={() => setUserId((prevId) => prevId + 1)}>Iterate user</button>
            <div>{JSON.stringify(data?.name)}</div>
            <div>{JSON.stringify(loading)}</div>
            <div>
                {JSON.stringify(error?.message)}, {JSON.stringify(error?.response)}, {JSON.stringify(error?.code)}
            </div>
        </div>
    );
};

export { UserDisplay };

// packages/vue-example/src/client/app/components/UserDisplay.vue
<template>
    <div>User display: {{ data }}</div>
    <div>Loading: {{ loading }}</div>
    <button @click="iterateUser">Iterate user</button>
    <button @click="refetch">Refetch</button>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { useQuery } from '../vue/useQuery';
import { userQuery } from '../requests/user';

export default defineComponent({
    setup() {
        const currentId = ref(1);

        const { loading, data, refetch } = useQuery(() =>
            userQuery({ requestParams: { pathParams: { id: currentId.value } } }),
        );

        return { loading, data, currentId, refetch };
    },
    methods: {
        iterateUser() {
            this.currentId = this.currentId + 1;
        },
    },
});
</script>
